### ISSUE TITLE
Running sdts_train: Error in while (abs(c_thold - d_thold) > tol) { :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by xenmind** [matrix-profile-foundation/tsmp#28]
Hi,

Love the package, great work. I have the latest package off github, and I can run the example code for sdts_train. I'm trying it with my own data. I am annotating with a smoothing algorithm that has one parameter to set it's sensitivity. The smoother called Zigzag (in package TTR) basically annotates runs of ups (i.e. 1) and downs (0). For higher values of the smoothing parameter, i.e. longer runs of ups and downs, I can use multiple and long windows in sdts_train, and everything works fine. When I decrease the smoothing parameter for shorter runs (that change direction more often) I can only use 1 very short window. With longer or multiple windows I get the error (during the second stage). What am I doing wrong? Does the sdts algo only work for classifying rare events/highly imbalanced classes? If you need some data/code to replicate, let me know.

Thanks,
Gavin.

**Comment by franzbischoff** [comment]
Hi! This error happens typically when LHS or RHS is NA (in this case the result of abs() or tol).
I'm working gradually to handle these exceptions, thanks for reporting.
Do you have a sample of your data that I can try that reproduce this error?

**Comment by xenmind** [comment]
Hey, thanks for the prompt response, I'll put something together tonight.

**Comment by franzbischoff** [comment]
Sure, if you want you may send me the data by e-mail (it's in the package description).
I don't know in this case, but maybe a [reprex](https://reprex.tidyverse.org/) could be useful?

**Comment by xenmind** [comment]
I tried reprex, but it's a real pain trying to get custom data into it. I'm sending code and data as direct links you can download from my Dropbox. The data is here, just save it to your working directory: https://www.dropbox.com/s/4iqld8wic584ukc/data.csv?dl=0 The code is here: https://www.dropbox.com/s/wqxjy79zz2kg3ri/tsmp_repro_eg1.r?dl=0 Note that I kept the windows the same, so when changing data size and smoothing parameter, the error is thrown. Also for Run 3, I found another unexplained error you can take a look at.

Cheers, Gavin.

**Comment by franzbischoff** [comment]
Got them, found the issues, I'll push a fix later today.

**Comment by xenmind** [comment]
Awesome.

**Comment by franzbischoff** [comment]
R is very stubborn about NA's... Almost done

**Comment by franzbischoff** [comment]
I'm pushing the current state to develop branch. I'm not happy yet since the R version still not agree 100% with MATLAB version. But it seems to work well. I tried all your examples, and they are working (the last one I stopped because was taking too much). Prediction is also working as expected. All cases gave me an F-1 score of 1 (the last one I don't know yet).

**Comment by xenmind** [comment]
Nice work man. I got the F1 score of 1 as well, I'm not very familiar with the measure. Isn't that too good to be true?

**Comment by franzbischoff** [comment]
The last example gave me this score:
```
$f_score
[1] 0.8

$precision
[1] 0.8571429

$recall
[1] 0.75
```

F-1 Score of 1 is the best you can get, means you retrieved all information (recall == 1) and all the information retrieved is correct (precision == 1). Is not "too good", it depends on the complexity of the task, if it is a simple task a good algorithm can achieve this score.

**Comment by franzbischoff** [comment]
Bug fixed, it's actually ok, and I confused the results from MATLAB with R and thought they were different. Long night :-)

**Comment by xenmind** [comment]
I ran all the examples without problem! Thanks for the F-1 explanation, it was better than the page I read that never explained it was relative to complexity. I'll make sure to report any further issues I may find. Cheers, Gavin.

**Comment by franzbischoff** [comment]
Hi. I'm not saying that F_score is related to complexity, just that if the problem is not too complex, a result of 1 is not a big deal.
This type of score is well known in data retrieval tasks since the true negatives are not significant. Imagine if you measure the accuracy (TP+TN)/(FP+TP+TN+FN), if TN is 100k and TP is 1, the result would be near 100% with no real utility.
Here the TN you can think as all the TS segments where there is no change, what indeed is much more than the segments where there are changes, so can get the same problem of inflated TN's and meaningless results if using accuracy.
