### ISSUE TITLE
R Shiny app for TSMP

### ISSUE THREAD

**Issue by franzbischoff** [matrix-profile-foundation/tsmp#31]

**Comment by awchisholm** [comment]
I could create a Shiny example if you still need this. It will be basic to start with.

**Comment by franzbischoff** [comment]
Sure, be welcome to contribute

**Comment by awchisholm** [comment]
This is the World's most basic matrix profile demo app - it's using the gait data

https://information-gain.shinyapps.io/tsmp-demo-shinyapp/

Rather than commit myself to making a push request and getting into discussions about where actually to put the files, better to start with the answer and then decide if it's helpful.

**Comment by franzbischoff** [comment]
Thank you for the collaboration.
I've finally read how to create shiny apps and published it at:
https://franzbischoff.shinyapps.io/tsmp/

Just a "hello world" like yours.

**Comment by awchisholm** [comment]
Hello

I realise I didn't share my code for the Shiny app - I can if you want
although I suspect you've made it up the learning curve now.

Does the new github repository for tsmp contain your "hello world" Shiny
example?

Andrew

**Comment by franzbischoff** [comment]
Yeah, I created a new repository on matrix profile foundation, currently
private. I did it using the golem framework.

--
Francisco Bischoff

*"O mate está para o gaúcho como o chá para os ingleses, a coca para os
bolivianos, o uísque para os escoceses e o café... para os brasileiros" *
*-- Eduardo Bueno*
